### ISSUE TITLE
Minions plugin support

### ISSUE THREAD

**Issue by efor89** [Rapha149/ArmorStandEditor#4]
### Is your feature request related to a problem?

```bash
yes, i have the problem that the editor gui open after i pickup a minion from my minion plugin.
(sneak and right click to pick up a minion and to open the armorstand editor)
then i can pick all the items from the minions replace the minion and do it again and again and again....
```

### What solution would you like?

can you make an implimentation for this minions plugin pls
that the as editor gui is not longer open if i pickup a minion.
https://builtbybit.com/resources/minions.7431/

### Describe alternatives you've considered

chancel the gui open if its a minion pls

### Any additional comments?

the dev of the Minions plugin tell me this.

they need to check if the event is cancelled. Specifically the PlayerInteractAtEntityEvent

**Comment by Rapha149** [comment]
I can't just add support for every other plugin out there, but I do check if the interact event is cancelled before I open the inventory (see for yourself in my [Events](https://github.com/Rapha149/ArmorStandEditor/blob/main/plugin/src/main/java/de/rapha149/armorstandeditor/Events.java#L80) class at line 80).

If the ArmorstandEditor inventory is opened than that either means that you don't cancel the event or that you cancel it but didn't specify an event priority which means that my event listener is fired before yours (I don't have a priority specified so any priority lower than NORMAL should work).
Honestly, from a plugin priced at $33.80 I would expect that you would have done that and I will therefore not provide you with the code to do this. If you are sure that you have implemented the two things I described than please send me a code snippet to confirm because I will not buy your plugin.

**Comment by efor89** [comment]
i am not the dev of the plugin i buy it from the dev.

**Comment by efor89** [comment]
so the dev of minions have to do something to fix this?

**Comment by Rapha149** [comment]
I have done what I can in order to make my plugin compatible with other plugins. I won't add more things to make it compatible with a specific plugin when the other plugin does not try to do the same. And I can't even make it compatible because I don't have access to the source code and won't pay 33 dollars to get the plugin.
This is a public Github issue, if you want this fixed you can share the link to this issue with the minions team so they can see my answers. For now, I won't be doing anything because I'm pretty sure that it's not my plugin that's the problem here.

**Comment by efor89** [comment]
ok ty i will talk to minions dev and hope he fix it.

**Comment by efor89** [comment]
btw your plugin is rly nice ty that it is free on spigotmc! ❤

**Comment by Rapha149** [comment]
You're welcome

**Comment by efor89** [comment]
i close the issue he has update the minions plugin and use now lowest prio for the event and it works.
ty :)
