### ISSUE TITLE
[Bug] Dupe moment ArmorStand

### ISSUE THREAD

**Issue by Savranchuk** [Rapha149/ArmorStandEditor#5]
### Plugin version

1.5.3

### Server software and version

1.20.1

### Steps to reproduce

```bash
https://youtu.be/W1msbk5stdM

Using the auto-clicker program it is possible to dupe an item
```

### Expected behaviour

I'm expecting a quick fix

### What is actually happening?

A player enters the server, sets up an armor stand and somehow dupes using a clicker

**Comment by Rapha149** [comment]
Is it important that you click on the saddle before clicking on the armor stand to give yourself the item? I couldn't see it that well in the video.
For now you could disable the feature to give yourself the armor stand item in the config or set a permission for that feature so that regular players can't use it anymore.

**Comment by Savranchuk** [comment]
Is it possible to check with the player if there is no such item in the inventory before adding?

**Comment by Rapha149** [comment]
Sorry for the late reply, but I was on vacation for a few weeks.
I was now able to reproduce the error and fix it using a synchronized thread to check if the item was already clicked before. If it still occurs for you or your users please reopen the issue.
The [update](https://www.spigotmc.org/resources/armorstandeditor.108120/update?update=557470) is now online.

Thanks for reporting the bug!
